### ISSUE TITLE
当为空且是字符串类型时候，默认为其生成主键

### ISSUE THREAD

**Issue by gx-russel** [734839030/seezoon-stack#17]
- issues

`AbstractCrudService.save`如果`id`为`null`的时候` instanceof String` 是`false`
`// 当为空且是字符串类型时候，默认为其生成主键
if (null == t.getId() && t.getId() instanceof String) {
                t.setId((PK)IdGen.uuid());
            }`

- fix
   `
    // 当为空且是字符串类型时候，默认为其生成主键
    if (null == t.getId()) {
        //拿到T的父类 BaseEntity<PK>
        ParameterizedType genericSuperclass = (ParameterizedType) t.getClass().getGenericSuperclass();
        //拿到BaseEntity的泛型 PK
        Type actualTypeArgument = genericSuperclass.getActualTypeArguments()[0];
        //类型等于String
        if (actualTypeArgument.getTypeName() == String.class.getTypeName()) {
            t.setId((PK) IdGen.uuid());
        }
    }
`

**Comment by 734839030** [comment]
嗯 建议不错，以前的框架是按你你提示的这样写，新框架的写法会不会更简洁有效呢。

https://github.com/734839030/seezoon-framework-all/blob/master/src/main/java/com/seezoon/framework/common/service/CrudService.java
