### ISSUE TITLE
tag2.0.1 运行过程记录

### ISSUE THREAD

**Issue by JackGirl** [734839030/seezoon-stack#23]
### db文件夹sql 用户表插入和实际字段不一致 
INSERT INTO `sys_user` VALUES (1, NULL, 'admin', '$2a$10$GOB1Kw.6noZYJ1i7BzwbvezlRafUoWqlSILIzXvBYeZURrKFdG2aO', '系统管理员', '132****3372', NULL , '734839030@qq.com', 1, 1, '2021-01-19 00:57:42', 1, '2021-04-16 02:11:55', '');

用户表16字段  少了新增的open_id 和 union_id

**Comment by JackGirl** [comment]
原方法 List.of jdk1.8使用 Arrays.asList   Path.of 改为 Paths.get    lambada T[]::new 直接修改为 newT[size]

**Comment by 734839030** [comment]
> ### db文件夹sql 用户表插入和实际字段不一致
> INSERT INTO `sys_user` VALUES (1, NULL, 'admin', '$2a$10$GOB1Kw.6noZYJ1i7BzwbvezlRafUoWqlSILIzXvBYeZURrKFdG2aO', '系统管理员', '132****3372', NULL , '[734839030@qq.com](mailto:734839030@qq.com)', 1, 1, '2021-01-19 00:57:42', 1, '2021-04-16 02:11:55', '');
> 
> 用户表16字段 少了新增的open_id 和 union_id

确实漏了 谢谢提醒
